AWSTemplateFormatVersion: '2010-09-09'
Description: Create a basic Ubuntu EC2 instance

Parameters:
  KeyName:
    Type: String
    Description: Name of an existing EC2 KeyPair for SSH access

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0ecb62995f68bb549
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref MySecurityGroup
